export const FORBIDDEN = Symbol.for('Forbidden')
export const USERNOTEXIST = Symbol.for('UserNotExist')
export const WRONGEMAILFOROTP = Symbol.for('WrongEmailForOTP')
export const OTPALREADYUSED = Symbol.for('OTPAlreadyUsed')
export const OTPERROR = Symbol.for('OTPError')
export const AGREEMENTNOTSIGNED = Symbol.for('AgreementNotSigned')
export const LACKOFBALANCE = Symbol.for('LackOfBalance')
